[package]
name = "bevy-basic-ui"
version = "0.4.4"
description = "A small manager for menus and huds"
authors = ["Ky Roberts", "Ky Roberts<kywinston@proton.me>"]
repository = "https://github.com/KyleWinston/bevy-ui"
license = "MIT OR Apache-2.0"
edition = "2021"
keywords = ["bevy", "menus", "ui"]
exclude = ["/examples"]

[dependencies]
bevy = { version = "^0.13.2", default-features = false, features = [
    # Bevy functionality:
    "multi-threaded",     # Run with multithreading
    "bevy_asset",         # Assets management
    "bevy_scene",         # Scenes management
    "bevy_winit",         # Window management (cross-platform Winit backend)
    "bevy_render",        # Rendering framework core
    "bevy_core_pipeline", # Common rendering abstractions
    "bevy_pbr",           # 3D (physically-based) rendering
    "bevy_gltf",          # GLTF 3D assets format support
    "bevy_text",          # Text/font rendering
    "bevy_ui",            # UI toolkit

    # File formats:
    "png", # PNG image format for simple 2D images


    # Platform-specific:
    "x11",                   # Linux: Support X11 windowing system
    "android_shared_stdcxx", # Android: use shared C++ library
    "webgl2",                # Web: use WebGL2 instead of WebGPU
] }

sickle_ui = { path = "crates/sickle_ui" }

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3


[profile.release]
codegen-units = 1
