[package]
name = "bevy-basic-ui"
version = "0.4.10"
description = "A small manager for menus and huds"
authors = ["Ky Roberts", "Ky Roberts<kywinston@proton.me>"]
repository = "https://github.com/KyleWinston/bevy-ui"
license = "MIT OR Apache-2.0"
edition = "2021"
keywords = ["bevy", "menus", "ui"]
exclude = ["/examples"]


[dependencies]
serde = { version = "1.0", features = ["derive"] }
bevy = { version = "0.13.2", default-features = false, features = [
    "dynamic_linking",
    "multi-threaded",  # Run with multithreading"bevy_asset",         # Assets management"bevy_scene",         # Scenes management"bevy_winit",         # Window management (cross-platform Winit backend)"bevy_render",
    "bevy_pbr",        # Rendering framework core"bevy_core_pipeline", # Common rendering abstractions"tonemapping_luts",
    "bevy_text",       # Text/font rendering"bevy_ui",            # UI toolkit"asset_processor",    # Asset processing"png",                # PNG image format for simple 2D images"x11",
] }
bevy_mod_picking = { version = "0.18.2", default_features = false, features = [
    "backend_bevy_ui",
    "backend_sprite",
    "selection",
] }
bevy_common_assets = { version = "0.10.0", features = ["toml"] }

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
