[package]
name = "bevy-basic-ui"
version = "0.3.2"
description = "A small manager for menu states"
authors = ["Ky Roberts", "Ky Roberts<kywinston@proton.me>"]
repository = "https://github.com/KyleWinston/bevy-ui"
license = "MIT OR Apache-2.0"
edition = "2021"
keywords = ["bevy", "menus","ui"]

[dependencies]
bevy = "^0.13"
